sudo: false
cache: bundler
script: bundle exec rake
rvm:
  - 2.1
  - 2.2
gemfile:
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.5.0.x
  - Gemfile
notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    secure: tXWWi0oBvnC+uoeIQuZTd2a5VPgn4l2NRpLMY091OgpSiAaoYRlypogsyjGeIFibMQgozq81r+9Jap4C81jAK19kGT/jXrJGw8JyBRmRfCW/Rj6Aq6Fh196oIQMBZEq6YlLGJPd6GXUN5I42t/Oe0j+OEDEBKl669C3a5nVUYxI=
