script: "bundle exec rake"
before_install: gem update --system
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - jruby
gemfile:
  - gemfiles/Gemfile-rails.3.0.x
  - gemfiles/Gemfile-rails.3.1.x
  - gemfiles/Gemfile-rails.3.2.x
  - Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: jruby
      gemfile: Gemfile
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "1jM45T9Qz66U8toE0hD+jlFrXq6tamt28sAcCwmE5DXw/tJUMhdAcWcjjOXi\nT/u/dIvLtsuF9epXzzk4+iyywTKa4wW33+GGd5AtdA7IZZI0y37VnaaTZBF3\nz+vEmQmGAT91VxUo6BOn9Xljb4qp5mBAR+Ug8PvCnmvKNxkMJxs="
