script: "bundle exec rake"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
gemfile:
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.5.0.x
  - Gemfile
matrix:
  allow_failures:
    - rvm: 2.2
      gemfile: gemfiles/Gemfile-rails.3.2.x
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.0.0
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.1
    gemfile: gemfiles/Gemfile-rails.5.0.x
  - rvm: 2.2
    gemfile: gemfiles/Gemfile-rails.5.0.x
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
      - secure: "1jM45T9Qz66U8toE0hD+jlFrXq6tamt28sAcCwmE5DXw/tJUMhdAcWcjjOXi\nT/u/dIvLtsuF9epXzzk4+iyywTKa4wW33+GGd5AtdA7IZZI0y37VnaaTZBF3\nz+vEmQmGAT91VxUo6BOn9Xljb4qp5mBAR+Ug8PvCnmvKNxkMJxs="
